INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Sixt', 'Paris, France', 'Compact', 45.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Sixt', 'Berlin, Germany', 'Sedan', 50.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Europcar', 'Rome, Italy', 'Convertible', 60.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Europcar', 'Barcelona, Spain', 'SUV', 55.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Avis', 'London, UK', 'Luxury', 80.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Avis', 'Amsterdam, Netherlands', 'Economy', 40.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Hertz', 'Dublin, Ireland', 'Minivan', 65.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Hertz', 'Vienna, Austria', 'Sedan', 50.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Enterprise', 'Prague, Czech Republic', 'SUV', 55.00);
INSERT INTO "car_rentals" ("rental_company", "location", "car_type", "price") VALUES ('Enterprise', 'Budapest, Hungary', 'Compact', 45.00);
